sudo: required
dist: trusty
group: deprecated-2017Q3
language: python
python:
  - "2.7"
  - "3.6"
services:
  - docker
env:
  matrix:
  - OS_TYPE=centos OS_VERSION=7
  global:
    - PATH="/usr/bin:$PATH"

notifications:
    on_success: always # default: change
    on_failure: never

before_install:
  - deactivate
  - sudo apt-get update -qq
  - sudo apt-get install -y -o Dpkg::Options::="--force-confnew" docker-ce

  - echo 'DOCKER_OPTS="-H tcp://127.0.0.1:2375 -H unix:///var/run/docker.sock -s devicemapper"' | sudo tee /etc/default/docker > /dev/null
  - sudo service docker restart
  - sleep 5
  - sudo docker pull centos:centos${OS_VERSION}

install:
  - sudo pip install docker-py
  - sudo apt-get install -y sshpass software-properties-common python-software-properties
  - sudo apt-add-repository -y ppa:ansible/ansible
  - sudo apt-get update -qq
  - sudo apt-get install -y ansible
  - sudo rm /usr/bin/python && sudo ln -s /usr/bin/python2.7 /usr/bin/python
  - ansible-galaxy install -r test/requirements.yml -p test/roles/
  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=test/roles/' > ansible.cfg

before_script: # configure a headless display to test plot generation
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  # Upstream Artemis works just as fine for this test
  - export AMQ_BROKER_DOWNLOAD_URL=http://www.apache.org/dist/activemq/activemq-artemis/2.1.0/apache-artemis-2.1.0-bin.zip
  - docker network ls
  - make test
